### ISSUE TITLE
Boot from volume deprecated content

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/docs-cloud-servers#146]
https://developer.rackspace.com/docs/cloud-servers/v2/developer-guide/#boot-from-volume section uses `block_device_mapping` field in request bodies. I think that is deprecated and should be replaced with `block_device_mapping_v2`. Please note that [openstack documentation](http://developer.openstack.org/api-ref-compute-v2.1.html#createServer) doesn't mention `block_device_mapping`.

**Comment by catlook** [comment]
Thanks!  I'll confirm and make appropriate corrections :)  -- Cat

**Comment by shannonmitchell** [comment]
It looks like they both work currently.  block_device_mapping(--block-device-mapping option in nova) uses a device name when creating which creates issues with various hypervisors. You need to create the volume before using block_device_mapping.

block_device_mapping_v2(--block-device option in nova) allows for more flexibility allowing for various source types(image, volume, snapshot & blank) and destination types(local or volume). This also supports more hypervisors and doesn't require a volume to be set up first.  

http://docs.openstack.org/developer/nova/block_device_mapping.html


### With block_device_mapping, you have to create the volume first from the looks of it. The '--block-device-mapping' option in nova uses it. ###

supernova ustest-ord volume-create 100 --volume-type=SSD --display-name=BFB-test-SSD --image-id=9f05acc9-6436-4e95-aad9-eaeff74be602

supernova ustest-ord boot --flavor performance1-4 --block-device-mapping vda=eb86e29c-3944-40ab-876d-542f5df791c4:::0 BFVServer -d


REQ: curl -i --insecure 'https://ord.servers.api.rackspacecloud.com/v2/<tenant removed>/os-volumes_boot' -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: python-novaclient" -H "X-Auth-Project-Id: <tenant removed>" -H "X-Auth-Token: <removed>" -d '{"server": {"name": "BFVServer", "imageRef": "", "block_device_mapping": [{"boot_index": 0, "uuid": "eb86e29c-3944-40ab-876d-542f5df791c4", "device_name": "vda", "source_type": "", "volume_id": "eb86e29c-3944-40ab-876d-542f5df791c4", "delete_on_termination": "0"}], "flavorRef": "performance1-4", "max_count": 1, "min_count": 1}}'


'{
  "server": 
  {
    "name": "BFVServer", 
    "imageRef": "", 
    "block_device_mapping": 
    [{
      "boot_index": 0, 
      "uuid": "eb86e29c-3944-40ab-876d-542f5df791c4", 
      "device_name": "vda", 
      "source_type": "", 
      "volume_id": "eb86e29c-3944-40ab-876d-542f5df791c4", 
      "delete_on_termination": "0"
    }], 
    "flavorRef": "performance1-4", 
    "max_count": 1, 
    "min_count": 1
  }
}'



### With block_device_mapping_v2, you can create the volume and server in 1 step. The '--block-device' option in nova uses it. ###

supernova ustest-ord boot --flavor performance1-4 --block-device source=image,id=9f05acc9-6436-4e95-aad9-eaeff74be602,dest=volume,size=100,shutdown=preserve,bootindex=0 BFVServer3 -d

REQ: curl -g -i --insecure -X POST https://ord.servers.api.rackspacecloud.com/v2/<tenant removed>/os-volumes_boot -H "User-Agent: python-novaclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: <removed>" -d '{"server": {"name": "BFVServer3", "imageRef": "", "block_device_mapping_v2": [{"boot_index": "0", "uuid": "9f05acc9-6436-4e95-aad9-eaeff74be602", "volume_size": "100", "source_type": "image", "destination_type": "volume", "delete_on_termination": false}], "flavorRef": "performance1-4", "max_count": 1, "min_count": 1}}'


'{
  "server": 
  {
    "name": "BFVServer3", 
    "imageRef": "", 
    "block_device_mapping_v2": 
    [{
      "boot_index": "0", 
      "uuid": "9f05acc9-6436-4e95-aad9-eaeff74be602", 
      "volume_size": "100", 
      "source_type": "image", 
      "destination_type": "volume", 
      "delete_on_termination": false
    }], 
    "flavorRef": "performance1-4", 
    "max_count": 1, 
    "min_count": 1
  }
}'

**Comment by catlook** [comment]
Awesome information, Shannon!  I'll work on folding into the doc, without muddying the waters too much :)

**Comment by catlook** [comment]
closed with PR #152
