### ISSUE TITLE
Incorrect types documented

### ISSUE THREAD

**Issue by pythonandchips** [rackerlabs/docs-cloud-servers#159]
I've been using the api to create and read from servers and there seems to be a few incorrect documented. For example on /server/{server_id} the wrong types are

- flavour: documented as uuid but is object
- image: documented as uuid but is object

Could these be updated and the other api enpoints checked and update if there is a mismatch.

**Comment by catlook** [comment]
Nice catch!  I'll get in there and correct it everywhere in the API ref!

**Comment by catlook** [comment]
Ok, these should be fixed, along with several others that I identified with a  quick looksee.  I'll continue looking for opportunity to validate the data types!
