### ISSUE TITLE
No 'Expand All' Option

### ISSUE THREAD

**Issue by aziouk** [rackerlabs/docs-cloud-servers#164]
Hey Racker,

I know I've raised this before, but I have noticed that there is still no expandall in the docs menu, which makes it more difficult to find documentation quickly for a customer when they need it, especially if a user is looking for something that they could find in the old API docs. This could be remedied by adding an expandall button for the menu tree. Is there anything we can do to make this expand all option available at all?

One other UI issue I could see was that you have to click on the rather small 'arrow' next to the menu text to make the menu element expand, perhaps it would be a lot better if clicking on the menu text automatically expanded the sub menu links below it as well as taking you to the link for that section, since this is much closer to the way API documentation was last year, seems faster and more efficient; well anyway at least myself and my team! We find it more usable that way.

Thank you very much for taking the time to read this! Have a great day & 💯 %

Best wishes,
Adam

**Comment by catlook** [comment]
Adam,

Thanks for bring this to our attention.  We're working with UX designers to improve the look and feel of our docs.  Unless I'm mistaking, easy expand and collapse options are on the list. Not sure about an expand/collapse all button, but let me check! Stay tuned!  The good news is that the Servers docs are going to be the beta release before we roll out to the other docs.  You should see much goodness in the next month or so :)  I'll keep you posted!

**Comment by aziouk** [comment]
Hey Cat,

You are most welcome & thank you so much for reaching back out so quickly, I really appreciate it!

If I recall the old version of the API docs were automatically expanded, which did take up more space, so now customers get a better general overview in the collapsed default, but really pleased expandall should be with us at some point, I think it will make a difference having that after discussing with my colleagues some months ago.  By having the collapsed default and the ability to expand and collapse all, I think we can get best of both worlds!

Thank you so much for your time Cat! Have a good one &

Best wishes,
Adam

**Comment by catlook** [comment]
Adam,

Ok, I had a quick consultation and unfortunately the exapnad all option is not possible.  Our old publishing platform included content in docbook and publishing via the maven plugin, The new platform we're on uses RST content and Sphinx for publishing.  This makes our docs mush easier to support and more accessible for contributions from everyone.  The drawback is that Sphinx does not support expand all.  Take a look at this doc and see if you can navigate it a bit easier than the current server docs: https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/load-balancers/  This version of th eLoad Balnacer docs is what we're moving towards!

**Comment by catlook** [comment]
@kmsholcomb and @cyrichardson, you might want to consider Adam's feedback :)

Adam, you can also look at https://staging.developer.rackspace.com/staging.horse/build-04ba0a18b4/docs/private-cloud/rpc/master/rpc-admin/ to see how the TOC is listed.

**Comment by meker12** [comment]
@aziouk Also, let us know if you like the full, expanded content being visible on the first page of the document.  Thanks for the feedback!

**Comment by aziouk** [comment]
Hey @Cat and @meker12 Meker12, thank you most kindly for passing our feedback along, it is much appreciated, really it was just something that I noticed and my colleagues agreed could maybe be a bit more accessible. I know you folks have been making a lot of changes to try and standardise the format so we try to give feedback where we can! We support a lot of cloud customers for API in the infrastructure team so we probably the first guys to notice changes to the docs! I think a part of it may be that we are used to a particular format vs another too.

I've taken a look at the the TOC and actually can't see a problem with a TOC instead of the expandall functions, since it basically provides the same thing! An itemised list of each section. The only item I would highlight in addition is perhaps this TOC is hiding away a bit, because it wasn't directly obvious to me where to find it. I struggled to find the TOC on this page for instance:

https://developer.rackspace.com/docs/cloud-servers/v2/developer-guide/#document-overview/index

I think if at the top of every API docs, a 'Table of Contents' tab was there, near or above getting started, it might make a usability difference, and it'd negate the fact that the expandall function was missing with Phinx, since it'd provide the same reference as the expandall, without having to change much. What do you think? It's just a thought, and maybe I was simply being silly and missed the TOC before, but the more obvious it is the better I suppose!

Have a great day! 

Thank you very much for your time folks &
Best wishes,
Adam

**Comment by catlook** [comment]
@aziouk Hey Adam!  The dust has finally settled and I think the docs are stable. We don't currently have resources to change the look and feel.  Hopefully, you'll find them easy to navigate.  The side bar allows you to expand and collapse sections and jump directly to your destination.  I'd like to go ahead and close this by Friday, but I'll let you weigh in for the record.

Here's the link to the current version: https://developer.rackspace.com/docs/cloud-servers/v2/getting-started/

**Comment by catlook** [comment]
Closing this.  Thanks.
