### ISSUE TITLE
Refactor API Guide PR preview not building content correctly

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-servers#173]
@smashwilson    Any idea why the [staging preview](https://staging.developer.rackspace.com/build-5777f3a3cf/docs/cloud-servers/v2/developer-guide/) doesn't have the table of contents or the previous and next buttons.

I think it might be related to the ``conf.py`` change from deconst serial builder to deconst single builder, but not sure. 

Follow up:  I think we went down this road before with the [RPC master branch](https://github.com/rackerlabs/nexus-control/issues/438).  Submitted a [nexus-control PR](https://github.com/rackerlabs/nexus-control/compare/master...meker12-patch-1?quick_pull=1) that might solve the problem.  @catlook

**Comment by smashwilson** [comment]
>I think it might be related to the `conf.py` change from deconst serial builder to deconst single builder, but not sure.

Yup, this is the cause. The serial and single builders put the TOC in different places, so the template you map in [config/routes.d](https://github.com/rackerlabs/nexus-control/blob/master/config/routes.d/developer.rackspace.com.json#L34) needs to match the builder for each repo. If I remember correctly, it's `docs-singlepage.html` for the single builder and `user-guide.html` for the serial builder.

**Comment by meker12** [comment]
@smashwilson Ack! I forgot about the template update!  Thank you.
