### ISSUE TITLE
nova volume-create is no longer available

### ISSUE THREAD

**Issue by martinb3** [rackerlabs/docs-cloud-servers#182]
It seems that the [docs describing boot from volume](https://developer.rackspace.com/docs/cloud-servers/v2/extensions/ext-boot-from-volume/) are referencing some commands that no longer exist in the nova command. 

[This doc](https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-interfaces/cli/cloudblockstorage-cli/) states that:
> In working with Cloud Block Storage, you might find that you need to use nova for some functions and cinder for others. You should install them both.

I'm guessing we need to update the cloud-servers docs with the cinder commands, or remove them and link to cinder docs directly.

**Comment by catlook** [comment]
Thanks, Martin.  I think adding a link is a great idea, so I'll do that next week!

**Comment by catlook** [comment]
Requested help from Trey and Sachin.  @martinb3, if you get this, maybe you can tell me which nova commands no longer work?  I don't want to actually document cinder commands in the servers doc, since that's a maintenance nightmare, but I will gladly link to them, if you can help me out!

**Comment by catlook** [comment]
closed with pr #184 

https://github.com/rackerlabs/docs-cloud-servers/pull/184
