### ISSUE TITLE
Listing images: incorrect url and missing CoreOS

### ISSUE THREAD

**Issue by gintautassulskus** [rackerlabs/docs-cloud-servers#189]
Hi,

I. The provided [tutorial](https://developer.rackspace.com/docs/cloud-servers/v2/getting-started/create-server/listing-images-curl/) refers to a wrong URL to list images.
The provided link 
```
curl -s https://$API_ENDPOINT/v2/$TENANT_ID/images/detail \
       -H "X-Auth-Token: $AUTH_TOKEN" | python -m json.tool
```
returns 
```
404 Not Found
No image found with ID detail
```
The link should be without _detail_ at the end as specified in the API reference.

II. The retrieved list is missing CoreOS image(s). Is this intended? How do I retrieve CoreOS image id?

Thanks,
Gin

**Comment by gintautassulskus** [comment]
All right, the second question is answered here: https://developer.rackspace.com/docs/cloud-block-storage/v1/general-api-info/paginated-collections/ 

The first issue still stands.

**Comment by catlook** [comment]
Thanks, I'll look into this for you!

**Comment by catlook** [comment]
closed with https://github.com/rackerlabs/docs-cloud-servers/pull/191
