### ISSUE TITLE
New bootable volume and server: unclear which parameters are optional

### ISSUE THREAD

**Issue by gintautassulskus** [rackerlabs/docs-cloud-servers#190]
Hi,

I am trying to create a bootable volume and a server via [REST API](https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-basic-operations/#create-bootable-volume-and-server). It is unclear, however, which parameters are optional. 
When _block_device_mapping_v2_ is specified all _block_device_mapping_v2.*_ fields are required. The documentation contradicts, stating that these fields are optional.

Cheers,
Gin

**Comment by catlook** [comment]
I'll research and clarify!

**Comment by catlook** [comment]
You are exactly right...those fields are optional in the general create a server operation (which could be the bootable version or not), but, for bootable, you absolutely need those fields (as you knew :))
