### ISSUE TITLE
API example for "Delete volume attachment from server" uses the incorrect field name.

### ISSUE THREAD

**Issue by robe6162** [rackerlabs/docs-cloud-servers#195]
**Doc Link**: https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-basic-operations/#delete-volume-attachment-from-server

The call listed in the documentation is: 
```
DELETE /servers/{server_id}/os-volume_attachments/{attachment_id}
```

**Issue**: the argument following the `/volume_attachments` is not the attachment_id, but rather the _volume_id_. 

The call should be:
```
DELETE /servers/{server_id}/os-volume_attachments/{volume_id}
```

The text describing the API call is correct: 
> In the URI, specify the target server ID and the target attached volume ID.

**Comment by catlook** [comment]
Thanks for catching this. I will correct!

**Comment by catlook** [comment]
and done!
