### ISSUE TITLE
Missing novnc console

### ISSUE THREAD

**Issue by inflatador** [rackerlabs/docs-cloud-servers#197]
The [current console example](https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-misc-operations/#get-console) only shows the older, Java-based console .

The HTML5-based novnc console is the preferred way to access console (used in the mycloud portal, among other places.). The call for the novnc console is as follows:

_'{"os-getVNCConsole": {"type": "novnc"}}'_

this is in nearly identical to the Java console call, which is 

_'{"os-getVNCConsole": {"type": "xvpnc"}}'_

**Comment by catlook** [comment]
done
