### ISSUE TITLE
Incorrect resizing info

### ISSUE THREAD

**Issue by inflatador** [rackerlabs/docs-cloud-servers#198]
https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-basic-operations/#resize-specified-server contains outdated information.

"The following list shows the availability of the resize operation for the flavor classes and server types:

Standard servers: can be resized to both smaller and larger sized servers.
General Purpose (formerly Performance 1) servers: can be resized to only larger sized servers.
All other flavors, OnMetal servers, and any server that boots from CBS volume – cannot be resized.
If you have a Compute, Memory, or IO flavor server, and you need to change the size of your data disk(s), you will need to:

Image your system disk.
Back-up your data disk(s), using Cloud Backup or Cloud Block Storage.
Create a new server with the desired size and flavor class, using your image.
Add your backed-up data to the new data disk(s).
Delete the old server, once you are satisfied with the new server."

All servers can resize up now, and very few can resize down. Recommend changing verbiage to the following:

 All Rackspace Cloud non-OnMetal servers (except I/O) can resize up. That covers:

- Compute
- General Purpose
- Memory
- Performance-1 (early version of GP, with slightly different disk allocation)
- Performance-2 (identical to I/O in everything except name)
- Standard
 
I/O flavors should be able to resize up very soon. Resize down is deprecated in Rackspace Cloud, and will only work for a subset of Linux servers on the Standard flavor.

**Comment by catlook** [comment]
Looks like Catherine fixed this, so I'm closing the issue.
