### ISSUE TITLE
(BFV) source_type must be volume when source is volume

### ISSUE THREAD

**Issue by joeashcraft** [rackerlabs/docs-cloud-servers#214]
when creating a server from an existing bootable volume, the "source_type" must be "volume".
otherwise, an error is returned because the UUID of the existing volume is not found in the list of images.

# invalid request example
## request
```
{
    "server": {
        "name": "bfv-test", 
        "flavorRef": "general1-2", 
        "block_device_mapping_v2": [
            {
                "boot_index": 0, 
                "uuid": "8de35732-f066-445f-9550-f8fcb975938a", 
                "source_type": "image", 
                "destination_type": "volume",
                "delete_on_termination": false,
            }
        ]
    }
}
```

## response body
```
{
    "badRequest": {
        "message": "Block Device Mapping is Invalid: failed to get image 8de35732-f066-445f-9550-f8fcb975938a.", 
        "code": 400
    }
}
```
# valid request example
## request
```
{
    "server": {
        "name": "bfv-test", 
        "flavorRef": "general1-2", 
        "block_device_mapping_v2": [
            {
                "boot_index": 0, 
                "uuid": "8de35732-f066-445f-9550-f8fcb975938a", 
                "source_type": "volume", 
                "destination_type": "volume",
                "delete_on_termination": false,
            }
        ]
    }
}
```
## response code
```
200 OK
```

# Defect
https://github.com/rackerlabs/docs-cloud-servers/blob/77b7ad79dafd438136c34a8010aa1c929eeea0cd/api-docs/extensions/ext-boot-from-volume.rst#L159
https://github.com/rackerlabs/docs-cloud-servers/blob/77b7ad79dafd438136c34a8010aa1c929eeea0cd/api-docs/extensions/ext-boot-from-volume.rst#L179

**Comment by catlook** [comment]
fixed in https://github.com/rackerlabs/docs-cloud-servers/pull/215.  Thanks, @joeashcraft !!
