### ISSUE TITLE
Format content that used to be in a table as a bullet list

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-servers#49]
On staging, under [How cURL commands work](http://staging.developer.rackspace.com/docs-cloud-servers/#how-curl-commands-work), the command-line options used to be in a table. Now they are just listed in text. However, they should be in a bulleted list for readability. Bullet the commands, and make the bulleted list that already exists under -H into a sublist.

**Comment by catlook** [comment]
done
