### ISSUE TITLE
Badly formatted link in Authentication

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-servers#51]
On staging, under [Authenticate with cURL](http://staging.developer.rackspace.com/docs-cloud-servers/#authenticate-with-curl): After the response example is a bullet list explaining some of the parts of the response. The bullet under "Endpoints to request Rackspace Cloud services" is formatted strangely! For a later revision, all of the main points should be in a bullet list, with the explanatory paragraphs under each bullet as indented paragraphs. For now, just make sure the entire "list" is formatted consistently and clearly.

**Comment by catlook** [comment]
done
