### ISSUE TITLE
Text possibly missing under "Absolute limits"

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-servers#52]
On staging, under [Absolute limits](http://staging.developer.rackspace.com/docs-cloud-servers/#absolute-limits): In the original doc, there is a second table in the section, for absolute total limits. There is not a corresponding list in the migrated doc. This could be on purpose, but I though I would point out the apparently missing information.

**Comment by catlook** [comment]
fixed
