### ISSUE TITLE
Bad indentation of bullet list under "Flavors"

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-servers#55]
On staging, under [Virtual Cloud Server flavors](http://staging.developer.rackspace.com/docs-cloud-servers/#virtual-cloud-server-flavors), the I/O v1, Compute v1, and Memory v1 list items are subordinated under General Purpose v1, rather than being shown as first-level bullets.

**Comment by catlook** [comment]
nope.  those are all virt flavors as opposed to the corresponding onmetal flavors.
