### ISSUE TITLE
Organization under "API Extensions" does not match original

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-servers#59]
This is nitpicky, but the original doc as a high-level section of "Rackspace Extensions" with all the individual extension sections subordinated under it. The migrated doc has a high-level section of "API Extensions."  "Rackspace Extensions" is subordinated under it, and then all the individual extension sections are at the same level as "Rackspace Extensions." I would suggest elevating the "Rackspace Extensions" content to the high-level section, so that the individual extension sections are clearly subordinated under it. That is, match the organization of the original doc, regardless of what you call the high-level section, "API Extensions" or "Rackspace Extensions."

**Comment by catlook** [comment]
this is intentional.
