### ISSUE TITLE
Example missing in extensions section

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-servers#60]
Compare [Changes to Create Server](http://staging.developer.rackspace.com/docs-cloud-servers/#changes-to-create-server) on staging to the origin doc. The origin doc has an example in the section, and the migrated doc links to an example. That's OK, but the wording in the section needs to change slightly (still refers to an example inline, which is not there). Also, the link should go right to the section it refers to, rather than to the top-level section.

**Comment by catlook** [comment]
done
