### ISSUE TITLE
"Retrieve list of key pairs" doesn't have a request example

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-servers#65]
[Retrieve list of key pairs](http://staging.developer.rackspace.com/docs-cloud-servers/#retrieve-list-of-key-pairs) doesn't have a request example. All the preceding operations have a request example, even if there is no request body, so this seems like an omission.

**Comment by catlook** [comment]
there is no body and no query params.  nothing to say here.
